[package]
name = "fink"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.3"
kube = { version = "0.88.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.21.0", features = ["latest"] }
tokio = { version = "1", features = ["full"] }


