apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.codesandbox.io
spec:
  group: codesandbox.io
  names:
    categories: []
    kind: VirtualMachine
    plural: virtualmachines
    shortNames:
    - vm
    singular: virtualmachine
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: VM rootfs image
      jsonPath: .spec.image
      name: Image
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: A VirtualMachine resource for FinK
        properties:
          spec:
            properties:
              image:
                type: string
              state:
                enum:
                - STOPPED
                - STARTED
                - HIBERNATED
                type: string
            required:
            - image
            - state
            type: object
          status:
            nullable: true
            properties:
              state:
                enum:
                - STOPPED
                - STOPPING
                - STARTED
                - STARTING
                - HIBERNATING
                - HIBERNATED
                type: string
            required:
            - state
            type: object
        required:
        - spec
        title: VirtualMachine
        type: object
    served: true
    storage: true
    subresources:
      status: {}
